// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Exercise struct {
	ID              int64
	Slug            string
	Name            string
	Kind            string
	DefaultSets     int64
	DefaultReps     int64
	DefaultWeightKg float64
	SortOrder       int64
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt string
	CreatedAt string
}

type Set struct {
	ID         int64
	WorkoutID  int64
	ExerciseID int64
	SetIndex   int64
	TargetReps int64
	ActualReps sql.NullInt64
	WeightKg   float64
}

type User struct {
	ID          int64
	GoogleSub   string
	Email       string
	Name        string
	CreatedAt   string
	LastLoginAt string
}

type UserExerciseHidden struct {
	UserID     int64
	ExerciseID int64
}

type UserExerciseSortOrder struct {
	UserID     int64
	ExerciseID int64
	SortOrder  int64
}

type UserExerciseWeight struct {
	UserID        int64
	ExerciseID    int64
	WeightKg      float64
	SuccessStreak int64
	UpdatedAt     string
}

type WalkingSession struct {
	WorkoutID   int64
	DurationMin int64
	SpeedX10    int64
	InclineX10  int64
}

type Workout struct {
	ID          int64
	UserID      int64
	WorkoutDate string
	CreatedAt   string
	CompletedAt sql.NullString
}
