// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const clearUserExerciseSortOrder = `-- name: ClearUserExerciseSortOrder :exec
DELETE FROM user_exercise_sort_order WHERE user_id = ?
`

func (q *Queries) ClearUserExerciseSortOrder(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearUserExerciseSortOrder, userID)
	return err
}

const countUntappedSetsInWorkout = `-- name: CountUntappedSetsInWorkout :one
SELECT COUNT(*) FROM sets WHERE workout_id = ? AND actual_reps IS NULL
`

// Counts sets that have never been tapped (actual_reps IS NULL). Used to
// decide whether a tap was the "last to complete" - i.e. the user filled in
// the final outstanding set, perhaps after going back to one they skipped.
func (q *Queries) CountUntappedSetsInWorkout(ctx context.Context, workoutID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUntappedSetsInWorkout, workoutID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserWorkouts = `-- name: CountUserWorkouts :one
SELECT COUNT(*) FROM workouts WHERE user_id = ?
`

func (q *Queries) CountUserWorkouts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserWorkouts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (token, user_id, expires_at, created_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt string
	CreatedAt string
}

// =============================================================================
// SESSIONS
// =============================================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSet = `-- name: CreateSet :exec
INSERT INTO sets (workout_id, exercise_id, set_index, target_reps, actual_reps, weight_kg)
VALUES (?, ?, ?, ?, NULL, ?)
`

type CreateSetParams struct {
	WorkoutID  int64
	ExerciseID int64
	SetIndex   int64
	TargetReps int64
	WeightKg   float64
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) error {
	_, err := q.db.ExecContext(ctx, createSet,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.SetIndex,
		arg.TargetReps,
		arg.WeightKg,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (google_sub, email, name, created_at, last_login_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	GoogleSub   string
	Email       string
	Name        string
	CreatedAt   string
	LastLoginAt string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.CreatedAt,
		arg.LastLoginAt,
	)
	return err
}

const createWorkout = `-- name: CreateWorkout :exec
INSERT INTO workouts (user_id, workout_date, created_at) VALUES (?, ?, ?)
`

type CreateWorkoutParams struct {
	UserID      int64
	WorkoutDate string
	CreatedAt   string
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, createWorkout, arg.UserID, arg.WorkoutDate, arg.CreatedAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts WHERE id = ? AND user_id = ?
`

type DeleteWorkoutParams struct {
	ID     int64
	UserID int64
}

// user_id check is defence in depth; handler already verifies ownership.
// ON DELETE CASCADE on sets and walking_sessions cleans up child rows.
func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const finishWorkout = `-- name: FinishWorkout :exec
UPDATE workouts SET completed_at = ? WHERE id = ? AND user_id = ?
`

type FinishWorkoutParams struct {
	CompletedAt sql.NullString
	ID          int64
	UserID      int64
}

func (q *Queries) FinishWorkout(ctx context.Context, arg FinishWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, finishWorkout, arg.CompletedAt, arg.ID, arg.UserID)
	return err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, slug, name, kind, default_sets, default_reps, default_weight_kg, sort_order
FROM exercises WHERE id = ?
`

func (q *Queries) GetExerciseByID(ctx context.Context, id int64) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.DefaultSets,
		&i.DefaultReps,
		&i.DefaultWeightKg,
		&i.SortOrder,
	)
	return i, err
}

const getLastSetIDInWorkout = `-- name: GetLastSetIDInWorkout :one
SELECT s.id
FROM sets s
JOIN exercises e ON e.id = s.exercise_id
LEFT JOIN user_exercise_sort_order uso
    ON uso.exercise_id = s.exercise_id AND uso.user_id = ?1
WHERE s.workout_id = ?2
ORDER BY COALESCE(uso.sort_order, e.sort_order) DESC,
         e.id DESC,
         s.set_index DESC
LIMIT 1
`

type GetLastSetIDInWorkoutParams struct {
	UserID    int64
	WorkoutID int64
}

// Returns the id of the very last set in user display order: among all sets
// in the workout, the one whose exercise has the largest effective sort_order
// (per-user override or global default), tie-broken by exercise id, and
// within that exercise the largest set_index. Used to suppress the rest
// timer on the final tap of the workout.
func (q *Queries) GetLastSetIDInWorkout(ctx context.Context, arg GetLastSetIDInWorkoutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastSetIDInWorkout, arg.UserID, arg.WorkoutID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLastUser = `-- name: GetLastUser :one
SELECT id, google_sub, email, name, created_at, last_login_at
FROM users WHERE id = (SELECT MAX(id) FROM users)
`

func (q *Queries) GetLastUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getLastUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getLastUserWalkingSession = `-- name: GetLastUserWalkingSession :one
SELECT ws.workout_id, ws.duration_min, ws.speed_x10, ws.incline_x10
FROM walking_sessions ws
JOIN workouts w ON w.id = ws.workout_id
WHERE w.user_id = ? AND w.workout_date < ?
ORDER BY w.workout_date DESC
LIMIT 1
`

type GetLastUserWalkingSessionParams struct {
	UserID      int64
	WorkoutDate string
}

func (q *Queries) GetLastUserWalkingSession(ctx context.Context, arg GetLastUserWalkingSessionParams) (WalkingSession, error) {
	row := q.db.QueryRowContext(ctx, getLastUserWalkingSession, arg.UserID, arg.WorkoutDate)
	var i WalkingSession
	err := row.Scan(
		&i.WorkoutID,
		&i.DurationMin,
		&i.SpeedX10,
		&i.InclineX10,
	)
	return i, err
}

const getLastWorkoutBefore = `-- name: GetLastWorkoutBefore :one
SELECT id, user_id, workout_date, created_at, completed_at
FROM workouts
WHERE user_id = ? AND workout_date < ?
ORDER BY workout_date DESC LIMIT 1
`

type GetLastWorkoutBeforeParams struct {
	UserID      int64
	WorkoutDate string
}

func (q *Queries) GetLastWorkoutBefore(ctx context.Context, arg GetLastWorkoutBeforeParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getLastWorkoutBefore, arg.UserID, arg.WorkoutDate)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutDate,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.google_sub, u.email, u.name, u.created_at, u.last_login_at,
       s.expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > ?
`

type GetSessionUserParams struct {
	Token     string
	ExpiresAt string
}

type GetSessionUserRow struct {
	ID          int64
	GoogleSub   string
	Email       string
	Name        string
	CreatedAt   string
	LastLoginAt string
	ExpiresAt   string
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.Token, arg.ExpiresAt)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSet = `-- name: GetSet :one
SELECT id, workout_id, exercise_id, set_index, target_reps, actual_reps, weight_kg
FROM sets WHERE id = ?
`

func (q *Queries) GetSet(ctx context.Context, id int64) (Set, error) {
	row := q.db.QueryRowContext(ctx, getSet, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetIndex,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightKg,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one


SELECT id, google_sub, email, name, created_at, last_login_at
FROM users WHERE google_sub = ?
`

// ASCII-only comments (sqlc/SQLite quirk).
// =============================================================================
// USERS
// =============================================================================
func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, name, created_at, last_login_at
FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserExerciseWeight = `-- name: GetUserExerciseWeight :one

SELECT user_id, exercise_id, weight_kg, success_streak, updated_at
FROM user_exercise_weight
WHERE user_id = ? AND exercise_id = ?
`

type GetUserExerciseWeightParams struct {
	UserID     int64
	ExerciseID int64
}

// =============================================================================
// USER EXERCISE WEIGHT
// =============================================================================
func (q *Queries) GetUserExerciseWeight(ctx context.Context, arg GetUserExerciseWeightParams) (UserExerciseWeight, error) {
	row := q.db.QueryRowContext(ctx, getUserExerciseWeight, arg.UserID, arg.ExerciseID)
	var i UserExerciseWeight
	err := row.Scan(
		&i.UserID,
		&i.ExerciseID,
		&i.WeightKg,
		&i.SuccessStreak,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalkingSession = `-- name: GetWalkingSession :one

SELECT workout_id, duration_min, speed_x10, incline_x10
FROM walking_sessions WHERE workout_id = ?
`

// =============================================================================
// WALKING SESSIONS
// =============================================================================
func (q *Queries) GetWalkingSession(ctx context.Context, workoutID int64) (WalkingSession, error) {
	row := q.db.QueryRowContext(ctx, getWalkingSession, workoutID)
	var i WalkingSession
	err := row.Scan(
		&i.WorkoutID,
		&i.DurationMin,
		&i.SpeedX10,
		&i.InclineX10,
	)
	return i, err
}

const getWorkoutByDate = `-- name: GetWorkoutByDate :one

SELECT id, user_id, workout_date, created_at, completed_at
FROM workouts
WHERE user_id = ? AND workout_date = ?
`

type GetWorkoutByDateParams struct {
	UserID      int64
	WorkoutDate string
}

// =============================================================================
// WORKOUTS
// =============================================================================
func (q *Queries) GetWorkoutByDate(ctx context.Context, arg GetWorkoutByDateParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByDate, arg.UserID, arg.WorkoutDate)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutDate,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, user_id, workout_date, created_at, completed_at
FROM workouts WHERE id = ?
`

func (q *Queries) GetWorkoutByID(ctx context.Context, id int64) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByID, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutDate,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const hideExercise = `-- name: HideExercise :exec
INSERT INTO user_exercise_hidden (user_id, exercise_id)
VALUES (?, ?)
ON CONFLICT(user_id, exercise_id) DO NOTHING
`

type HideExerciseParams struct {
	UserID     int64
	ExerciseID int64
}

func (q *Queries) HideExercise(ctx context.Context, arg HideExerciseParams) error {
	_, err := q.db.ExecContext(ctx, hideExercise, arg.UserID, arg.ExerciseID)
	return err
}

const listExercises = `-- name: ListExercises :many

SELECT id, slug, name, kind, default_sets, default_reps, default_weight_kg, sort_order
FROM exercises ORDER BY sort_order
`

// =============================================================================
// EXERCISES
// =============================================================================
// Global order. Used by progression code where order does not matter.
func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.DefaultSets,
			&i.DefaultReps,
			&i.DefaultWeightKg,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesForUser = `-- name: ListExercisesForUser :many
SELECT e.id, e.slug, e.name, e.kind, e.default_sets, e.default_reps, e.default_weight_kg, e.sort_order
FROM exercises e
LEFT JOIN user_exercise_sort_order uso
    ON uso.exercise_id = e.id AND uso.user_id = ?
ORDER BY COALESCE(uso.sort_order, e.sort_order), e.id
`

// Per-user order: rows in user_exercise_sort_order override exercises.sort_order.
// Exercises without a per-user row fall back to the seeded default.
func (q *Queries) ListExercisesForUser(ctx context.Context, userID int64) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.DefaultSets,
			&i.DefaultReps,
			&i.DefaultWeightKg,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiddenExerciseIDs = `-- name: ListHiddenExerciseIDs :many

SELECT exercise_id FROM user_exercise_hidden WHERE user_id = ?
`

// =============================================================================
// USER EXERCISE HIDDEN
// =============================================================================
func (q *Queries) ListHiddenExerciseIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listHiddenExerciseIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var exercise_id int64
		if err := rows.Scan(&exercise_id); err != nil {
			return nil, err
		}
		items = append(items, exercise_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsForWorkout = `-- name: ListSetsForWorkout :many

SELECT id, workout_id, exercise_id, set_index, target_reps, actual_reps, weight_kg
FROM sets WHERE workout_id = ?
ORDER BY exercise_id, set_index
`

// =============================================================================
// SETS
// =============================================================================
func (q *Queries) ListSetsForWorkout(ctx context.Context, workoutID int64) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, listSetsForWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetIndex,
			&i.TargetReps,
			&i.ActualReps,
			&i.WeightKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsForWorkoutExercise = `-- name: ListSetsForWorkoutExercise :many
SELECT id, workout_id, exercise_id, set_index, target_reps, actual_reps, weight_kg
FROM sets WHERE workout_id = ? AND exercise_id = ?
ORDER BY set_index
`

type ListSetsForWorkoutExerciseParams struct {
	WorkoutID  int64
	ExerciseID int64
}

func (q *Queries) ListSetsForWorkoutExercise(ctx context.Context, arg ListSetsForWorkoutExerciseParams) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, listSetsForWorkoutExercise, arg.WorkoutID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetIndex,
			&i.TargetReps,
			&i.ActualReps,
			&i.WeightKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsForWorkoutIDs = `-- name: ListSetsForWorkoutIDs :many
SELECT id, workout_id, exercise_id, set_index, target_reps, actual_reps, weight_kg
FROM sets
WHERE workout_id IN (/*SLICE:workout_ids*/?)
ORDER BY workout_id DESC, exercise_id, set_index
`

func (q *Queries) ListSetsForWorkoutIDs(ctx context.Context, workoutIds []int64) ([]Set, error) {
	query := listSetsForWorkoutIDs
	var queryParams []interface{}
	if len(workoutIds) > 0 {
		for _, v := range workoutIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workout_ids*/?", strings.Repeat(",?", len(workoutIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workout_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetIndex,
			&i.TargetReps,
			&i.ActualReps,
			&i.WeightKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserExerciseWeights = `-- name: ListUserExerciseWeights :many
SELECT exercise_id, weight_kg, success_streak
FROM user_exercise_weight WHERE user_id = ?
`

type ListUserExerciseWeightsRow struct {
	ExerciseID    int64
	WeightKg      float64
	SuccessStreak int64
}

func (q *Queries) ListUserExerciseWeights(ctx context.Context, userID int64) ([]ListUserExerciseWeightsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserExerciseWeights, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserExerciseWeightsRow
	for rows.Next() {
		var i ListUserExerciseWeightsRow
		if err := rows.Scan(&i.ExerciseID, &i.WeightKg, &i.SuccessStreak); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWalkingHistory = `-- name: ListUserWalkingHistory :many
SELECT w.id AS workout_id, w.workout_date,
       ws.duration_min, ws.speed_x10, ws.incline_x10,
       s.actual_reps
FROM walking_sessions ws
JOIN workouts w ON w.id = ws.workout_id
LEFT JOIN sets s ON s.workout_id = w.id AND s.exercise_id = ?
WHERE w.user_id = ?
ORDER BY w.workout_date DESC
LIMIT ?
`

type ListUserWalkingHistoryParams struct {
	ExerciseID int64
	UserID     int64
	Limit      int64
}

type ListUserWalkingHistoryRow struct {
	WorkoutID   int64
	WorkoutDate string
	DurationMin int64
	SpeedX10    int64
	InclineX10  int64
	ActualReps  sql.NullInt64
}

func (q *Queries) ListUserWalkingHistory(ctx context.Context, arg ListUserWalkingHistoryParams) ([]ListUserWalkingHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserWalkingHistory, arg.ExerciseID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserWalkingHistoryRow
	for rows.Next() {
		var i ListUserWalkingHistoryRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.DurationMin,
			&i.SpeedX10,
			&i.InclineX10,
			&i.ActualReps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkoutsPaged = `-- name: ListUserWorkoutsPaged :many
SELECT id, user_id, workout_date, created_at, completed_at
FROM workouts
WHERE user_id = ?
ORDER BY workout_date DESC
LIMIT ? OFFSET ?
`

type ListUserWorkoutsPagedParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListUserWorkoutsPaged(ctx context.Context, arg ListUserWorkoutsPagedParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listUserWorkoutsPaged, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutDate,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkoutsSince = `-- name: ListUserWorkoutsSince :many
SELECT id, workout_date, completed_at
FROM workouts
WHERE user_id = ? AND workout_date >= ?
ORDER BY workout_date DESC
`

type ListUserWorkoutsSinceParams struct {
	UserID      int64
	WorkoutDate string
}

type ListUserWorkoutsSinceRow struct {
	ID          int64
	WorkoutDate string
	CompletedAt sql.NullString
}

func (q *Queries) ListUserWorkoutsSince(ctx context.Context, arg ListUserWorkoutsSinceParams) ([]ListUserWorkoutsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserWorkoutsSince, arg.UserID, arg.WorkoutDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserWorkoutsSinceRow
	for rows.Next() {
		var i ListUserWorkoutsSinceRow
		if err := rows.Scan(&i.ID, &i.WorkoutDate, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightHistoryForExercise = `-- name: ListWeightHistoryForExercise :many
SELECT w.id AS workout_id, w.workout_date,
       s.weight_kg, s.set_index, s.target_reps, s.actual_reps
FROM sets s
JOIN workouts w ON w.id = s.workout_id
WHERE w.user_id = ? AND s.exercise_id = ?
ORDER BY w.workout_date DESC, s.set_index
LIMIT ?
`

type ListWeightHistoryForExerciseParams struct {
	UserID     int64
	ExerciseID int64
	Limit      int64
}

type ListWeightHistoryForExerciseRow struct {
	WorkoutID   int64
	WorkoutDate string
	WeightKg    float64
	SetIndex    int64
	TargetReps  int64
	ActualReps  sql.NullInt64
}

func (q *Queries) ListWeightHistoryForExercise(ctx context.Context, arg ListWeightHistoryForExerciseParams) ([]ListWeightHistoryForExerciseRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeightHistoryForExercise, arg.UserID, arg.ExerciseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeightHistoryForExerciseRow
	for rows.Next() {
		var i ListWeightHistoryForExerciseRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WeightKg,
			&i.SetIndex,
			&i.TargetReps,
			&i.ActualReps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfinishWorkout = `-- name: UnfinishWorkout :exec
UPDATE workouts SET completed_at = NULL WHERE id = ? AND user_id = ? AND workout_date = ?
`

type UnfinishWorkoutParams struct {
	ID          int64
	UserID      int64
	WorkoutDate string
}

func (q *Queries) UnfinishWorkout(ctx context.Context, arg UnfinishWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, unfinishWorkout, arg.ID, arg.UserID, arg.WorkoutDate)
	return err
}

const unhideExercise = `-- name: UnhideExercise :exec
DELETE FROM user_exercise_hidden WHERE user_id = ? AND exercise_id = ?
`

type UnhideExerciseParams struct {
	UserID     int64
	ExerciseID int64
}

func (q *Queries) UnhideExercise(ctx context.Context, arg UnhideExerciseParams) error {
	_, err := q.db.ExecContext(ctx, unhideExercise, arg.UserID, arg.ExerciseID)
	return err
}

const updateSetActualReps = `-- name: UpdateSetActualReps :exec
UPDATE sets SET actual_reps = ?
WHERE sets.id = ?
  AND sets.workout_id IN (SELECT w.id FROM workouts w WHERE w.user_id = ?)
`

type UpdateSetActualRepsParams struct {
	ActualReps sql.NullInt64
	ID         int64
	UserID     int64
}

// user_id check is defence in depth; handlers already verify ownership.
func (q *Queries) UpdateSetActualReps(ctx context.Context, arg UpdateSetActualRepsParams) error {
	_, err := q.db.ExecContext(ctx, updateSetActualReps, arg.ActualReps, arg.ID, arg.UserID)
	return err
}

const updateSetsWeightForExercise = `-- name: UpdateSetsWeightForExercise :exec
UPDATE sets SET weight_kg = ?
WHERE sets.workout_id = ? AND sets.exercise_id = ?
  AND sets.workout_id IN (SELECT w.id FROM workouts w WHERE w.user_id = ?)
`

type UpdateSetsWeightForExerciseParams struct {
	WeightKg   float64
	WorkoutID  int64
	ExerciseID int64
	UserID     int64
}

func (q *Queries) UpdateSetsWeightForExercise(ctx context.Context, arg UpdateSetsWeightForExerciseParams) error {
	_, err := q.db.ExecContext(ctx, updateSetsWeightForExercise,
		arg.WeightKg,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.UserID,
	)
	return err
}

const updateUserExerciseWeightOnly = `-- name: UpdateUserExerciseWeightOnly :exec
UPDATE user_exercise_weight
SET weight_kg = ?, updated_at = ?
WHERE user_id = ? AND exercise_id = ?
`

type UpdateUserExerciseWeightOnlyParams struct {
	WeightKg   float64
	UpdatedAt  string
	UserID     int64
	ExerciseID int64
}

func (q *Queries) UpdateUserExerciseWeightOnly(ctx context.Context, arg UpdateUserExerciseWeightOnlyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserExerciseWeightOnly,
		arg.WeightKg,
		arg.UpdatedAt,
		arg.UserID,
		arg.ExerciseID,
	)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = ? WHERE id = ?
`

type UpdateUserLastLoginParams struct {
	LastLoginAt string
	ID          int64
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const upsertExercise = `-- name: UpsertExercise :exec
INSERT INTO exercises (slug, name, kind, default_sets, default_reps, default_weight_kg, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    name = excluded.name,
    kind = excluded.kind,
    default_sets = excluded.default_sets,
    default_reps = excluded.default_reps
`

type UpsertExerciseParams struct {
	Slug            string
	Name            string
	Kind            string
	DefaultSets     int64
	DefaultReps     int64
	DefaultWeightKg float64
	SortOrder       int64
}

// sort_order is intentionally only set on initial INSERT so that user
// reordering on the settings page is not clobbered by the seed on restart.
func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) error {
	_, err := q.db.ExecContext(ctx, upsertExercise,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.DefaultSets,
		arg.DefaultReps,
		arg.DefaultWeightKg,
		arg.SortOrder,
	)
	return err
}

const upsertUserExerciseSortOrder = `-- name: UpsertUserExerciseSortOrder :exec
INSERT INTO user_exercise_sort_order (user_id, exercise_id, sort_order)
VALUES (?, ?, ?)
ON CONFLICT(user_id, exercise_id) DO UPDATE SET
    sort_order = excluded.sort_order
`

type UpsertUserExerciseSortOrderParams struct {
	UserID     int64
	ExerciseID int64
	SortOrder  int64
}

func (q *Queries) UpsertUserExerciseSortOrder(ctx context.Context, arg UpsertUserExerciseSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserExerciseSortOrder, arg.UserID, arg.ExerciseID, arg.SortOrder)
	return err
}

const upsertUserExerciseWeight = `-- name: UpsertUserExerciseWeight :exec
INSERT INTO user_exercise_weight (user_id, exercise_id, weight_kg, success_streak, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, exercise_id) DO UPDATE SET
    weight_kg = excluded.weight_kg,
    success_streak = excluded.success_streak,
    updated_at = excluded.updated_at
`

type UpsertUserExerciseWeightParams struct {
	UserID        int64
	ExerciseID    int64
	WeightKg      float64
	SuccessStreak int64
	UpdatedAt     string
}

func (q *Queries) UpsertUserExerciseWeight(ctx context.Context, arg UpsertUserExerciseWeightParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserExerciseWeight,
		arg.UserID,
		arg.ExerciseID,
		arg.WeightKg,
		arg.SuccessStreak,
		arg.UpdatedAt,
	)
	return err
}

const upsertWalkingSession = `-- name: UpsertWalkingSession :exec
INSERT INTO walking_sessions (workout_id, duration_min, speed_x10, incline_x10)
SELECT w.id,
       ?1,
       ?2,
       ?3
FROM workouts w
WHERE w.id = ?4 AND w.user_id = ?5
ON CONFLICT(workout_id) DO UPDATE SET
    duration_min = excluded.duration_min,
    speed_x10    = excluded.speed_x10,
    incline_x10  = excluded.incline_x10
`

type UpsertWalkingSessionParams struct {
	DurationMin int64
	SpeedX10    int64
	InclineX10  int64
	WorkoutID   int64
	UserID      int64
}

// The SELECT yields zero rows (and therefore writes nothing) if the workout
// does not belong to user_id. Handlers already check ownership; this is
// defence in depth.
func (q *Queries) UpsertWalkingSession(ctx context.Context, arg UpsertWalkingSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertWalkingSession,
		arg.DurationMin,
		arg.SpeedX10,
		arg.InclineX10,
		arg.WorkoutID,
		arg.UserID,
	)
	return err
}
